name: superspec-workflow
version: 2
description: |
  SuperSpec unified spec-driven development workflow.

  Flow: brainstorm → plan → execute → verify → archive

  Brainstorm is a progressive flow: Explore → Propose → Design → Spec

artifacts:
  # ============================================
  # Phase 1: Brainstorm (Explore → Propose → Design → Spec)
  # ============================================
  - id: brainstorm
    generates:
      - proposal.md
      - design.md
      - "specs/**/*.md"
    description: |
      Progressive design flow from exploration to specifications.
      Four phases: Explore → Propose → Design → Spec
    instruction: |
      Use the brainstorm skill for a progressive flow:

      **Phase 1: EXPLORE**
      - Free-form exploration
      - Ask clarifying questions (one at a time)
      - Investigate codebase
      - Visualize with ASCII diagrams
      - Challenge assumptions

      Transition: "Problem is clear enough, let's define the change scope"

      **Phase 2: PROPOSE**
      - Define Why (problem/opportunity)
      - Define What Changes
      - Define Capabilities (new/modified)
      - Define Impact
      - Generate proposal.md

      Transition: "Change scope is defined, let's design the technical approach"

      **Phase 3: DESIGN**
      - Present 2-3 approaches with trade-offs
      - Compare and recommend
      - Document technical decisions
      - Generate design.md

      Transition: "Technical approach is decided, let's define the specifications"

      **Phase 4: SPEC**
      - Define Requirements (system SHALL...)
      - Define Scenarios (WHEN/THEN) - each becomes a test
      - Generate specs/*.md

      Output:
      - superspec/changes/[id]/proposal.md
      - superspec/changes/[id]/design.md
      - superspec/changes/[id]/specs/[capability]/spec.md
    requires: []

  # ============================================
  # Phase 2: Planning
  # ============================================
  - id: plan
    generates: plan.md
    description: TDD implementation plan based on Specs
    template: plan.md
    instruction: |
      Create TDD implementation plan. Each Scenario becomes a test.

      Structure for each task:
      - **Spec Reference**: Link to Requirement and Scenario
      - **Files**: Create/Modify/Test paths
      - **Step 1**: Write failing test (RED) - based on Scenario
      - **Step 2**: Run to verify failure
      - **Step 3**: Implement minimal code (GREEN)
      - **Step 4**: Run to verify pass
      - **Step 5**: Refactor (if needed)
      - **Step 6**: Commit with Spec reference

      Scenario → Test mapping:
      ```
      #### Scenario: Valid login       →  test('Valid login', () => {
      - WHEN valid credentials              // WHEN
      - THEN grants access                  expect(login(valid).granted).toBe(true);
                                          });
      ```
    requires:
      - brainstorm

  - id: tasks
    generates: tasks.md
    description: Implementation task checklist
    template: tasks.md
    instruction: |
      Create task checklist from plan.md.

      Format:
      - [ ] X.Y Write test for Scenario: [name]
        - Spec: Requirement X → Scenario Y
      - [ ] X.Z Implement [feature]
      - [ ] X.W Commit

      Each task: 2-5 minutes, verifiable, references Spec.
    requires:
      - plan

# ============================================
# Apply Phase: TDD Implementation
# ============================================
apply:
  requires: [tasks]
  tracks: tasks.md
  instruction: |
    Execute plan using TDD and subagent-driven development.

    **Per Task Flow:**
    1. Dispatch Implementer subagent
       - TDD: Write test (RED) → Implement (GREEN) → Refactor
       - Self-review

    2. Dispatch Spec Reviewer subagent
       - Verify: Implementation matches Requirement + Scenarios
       - Check: No missing features, no extra features

    3. Dispatch Quality Reviewer (after spec passes)
       - Check: Error handling, type safety, SOLID
       - Classify: Critical / Important / Suggestion

    4. Mark task complete

    After all tasks: Final code review.

# ============================================
# Verify Phase
# ============================================
verify:
  requires: [apply]
  instruction: |
    Verify implementation matches specifications.

    Checks:
    1. Every Requirement has implementation
    2. Every Scenario has test
    3. All tests pass
    4. No features outside Specs

    Run: `superspec validate [change-id] --strict`

# ============================================
# Archive Phase
# ============================================
archive:
  requires: [verify]
  instruction: |
    Archive change and apply deltas to main specs.

    Steps:
    1. Verify all tests pass
    2. Apply Deltas to superspec/specs/
    3. Move to superspec/changes/archive/YYYY-MM-DD-[id]/
    4. Finish branch (merge/PR/keep/discard)
    5. Clean up worktree

    Run: `superspec archive [change-id] --yes`
